CREATE TABLE Auth (
	Email NVARCHAR(100) PRIMARY KEY,
    PasswordHash NVARCHAR(255) NOT NULL,
    PasswordSalt NVARCHAR(255) NOT NULL,
    LastLogin DATETIME NULL,
    FOREIGN KEY (Email) REFERENCES Users(Email) ON DELETE CASCADE
);
