CREATE TABLE Users(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(50) NOT NULL UNIQUE,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    Bio NVARCHAR(50) NULL,
    AvatarUrl NVARCHAR(255) NULL,
    RoleType NVARCHAR(20) NOT NULL DEFAULT 'User',
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    IsBanned BIT NOT NULL DEFAULT 0
)


