CREATE TABLE Posts(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    AuthorId UNIQUEIDENTIFIER NOT NULL,
    Title NVARCHAR(200) NOT NULL,
    Slug NVARCHAR(200) NOT NULL UNIQUE,
    Content NVARCHAR(MAX) NOT NULL,
    ImageUrl NVARCHAR(255),
    ViewCount INT NOT NULL DEFAULT 0,
    CategoryId INT NULL,
    CreateAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME NULL,
    CONSTRAINT FK_Posts_Categories FOREIGN KEY (CategoryId) REFERENCES Categories(Id) ON DELETE SET NULL,
    CONSTRAINT FK_Posts_Users FOREIGN KEY (AuthorId) REFERENCES Users(Id) ON DELETE CASCADE
     
)